## Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "roles": [
    "ADMIN",
    "TEACHER"
  ]
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Refresh Token
GET http://localhost:3000/auth/refresh-token?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1YWFjNzcxLTg0MGQtNDJmYy05ODI0LTViMzMzNjI5NmExNyIsInJvbGVzIjpbIkFETUlOIiwiVEVBQ0hFUiJdLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTkwNDI2NDM0LCJleHAiOjE1OTMwMTg0MzR9.lsLVGaAGpH9I2YLZMrMjJxhZ1oAQpKTVtVoOXxZkOPI
Accept: application/json

### Role
GET http://localhost:3000/roles
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2M2U2MzljLTkxMDEtNDYyZC04OGNkLWQxY2NjNDI5Yzc5MyIsInJvbGVzIjpbIkFETUlOIiwiVEVBQ0hFUiJdLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTkwNDYyOTc0LCJleHAiOjE1OTA0NjM4NzR9.kxZan7BDX8Ml_z3KUxY392ypF5QoZ99g5PTotHaahV4

### Menus
GET http://localhost:3000/menus
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2M2U2MzljLTkxMDEtNDYyZC04OGNkLWQxY2NjNDI5Yzc5MyIsInJvbGVzIjpbIkFETUlOIiwiVEVBQ0hFUiJdLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTkwNDYyOTc0LCJleHAiOjE1OTA0NjM4NzR9.kxZan7BDX8Ml_z3KUxY392ypF5QoZ99g5PTotHaahV4

###
