## Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "roles": [
    "ADMIN",
    "TEACHER"
  ]
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Refresh Token
GET http://localhost:3000/auth/refresh-token?refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1YWFjNzcxLTg0MGQtNDJmYy05ODI0LTViMzMzNjI5NmExNyIsInJvbGVzIjpbIkFETUlOIiwiVEVBQ0hFUiJdLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTkwNDI2NDM0LCJleHAiOjE1OTMwMTg0MzR9.lsLVGaAGpH9I2YLZMrMjJxhZ1oAQpKTVtVoOXxZkOPI
Accept: application/json


### Role
GET http://localhost:3000/auth/roles
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJBRE1JTiIsIlRFQUNIRVIiXSwidXNlcm5hbWUiOiJhZG1pbiIsInByb2ZpbGVOYW1lIjoiR3Vlc3QiLCJpYXQiOjE1OTAzODg5NzcsImV4cCI6MTU5MDQzMjE3N30.XVrK56dUpO-djNPuPfO9CGERqrN2AgpgGFI6pPAPagM

### Menu
GET http://localhost:3000/auth/menus
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJBRE1JTiIsIlRFQUNIRVIiXSwidXNlcm5hbWUiOiJhZG1pbiIsInByb2ZpbGVOYW1lIjoiR3Vlc3QiLCJpYXQiOjE1OTAzODg5NzcsImV4cCI6MTU5MDQzMjE3N30.XVrK56dUpO-djNPuPfO9CGERqrN2AgpgGFI6pPAPagM
###
